import fs from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
import assert from 'node:assert/strict';
import {chromium, expect} from '@playwright/test';
const base=process.argv[2] || '/';
const root=path.resolve('dist');
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.webp':'image/webp','.mp4':'video/mp4','.json':'application/json'};
const server=http.createServer(async(request,response)=>{
  try{
    const pathname=new URL(request.url,'http://localhost').pathname;
    if(!pathname.startsWith(base))throw new Error('Outside base');
    let file=path.resolve(root,decodeURIComponent(pathname.slice(base.length)));
    if(file!==root&&!file.startsWith(root+path.sep))throw new Error('Outside output');
    if((await fs.stat(file)).isDirectory())file=path.join(file,'index.html');
    response.setHeader('Content-Type',types[path.extname(file)]||'application/octet-stream');response.end(await fs.readFile(file));
  }catch{response.writeHead(404);response.end('Not found');}
});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const address=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({channel:'chrome'});
try{
  const page=await browser.newPage();const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('response',response=>{if(response.status()>=400)errors.push(response.status()+' '+response.url());});
  await page.addInitScript(()=>localStorage.setItem('pi-motion','off'));
  await page.goto(address+base);await page.waitForSelector('html[data-enhanced]');
  await page.locator('#projects').evaluate(element=>element.scrollIntoView({block:'start'}));
  await expect(page.locator('.site-header')).toHaveAttribute('data-theme','light');
  await expect(page.locator('.site-header')).toHaveCSS('backdrop-filter','blur(24px) saturate(1.1)');
  const links=await page.locator('.project-link').evaluateAll(els=>els.map(el=>el.getAttribute('href')));
  assert.equal(links.length,30);assert(links.every(href=>href.startsWith(base)));
  for(const href of links){const response=await page.request.get(address+href);assert.equal(response.status(),200,href);}
  await page.locator('[data-featured-view="seton-crossing"]').click();
  await expect(page.locator('[data-featured-image]')).toHaveAttribute('src',base+'media/gallery/seton-crossing/2.webp');
  await expect(page.locator('[data-featured-detail]')).toHaveAttribute('src',base+'media/gallery/seton-crossing/usb-img_2443.webp');
  await page.locator('[data-detail-select="paths"]').click();
  await expect(page.locator('#detail-plan-image')).toHaveAttribute('src',base+'media/gallery/evanston/3.webp');
  await expect(page.locator('#detail-project-link')).toHaveAttribute('href',base+'evanston');
  await page.locator('.detail-desk-links [data-open-drawing]').click();
  await expect(page.locator('#detail-viewer-image')).toHaveAttribute('src',base+'media/gallery/evanston/3.webp');
  await page.locator('#detail-viewer-zoom').click();
  await expect(page.locator('#detail-drawing-viewer')).toHaveAttribute('data-zoom','true');
  await page.keyboard.press('Escape');
  await page.locator('[data-menu-trigger="projects"]').click();
  await page.locator('button[data-catalogue-open]').click();
  const catalogueLinks=await page.locator('[data-catalogue-project]').evaluateAll(els=>els.map(el=>el.getAttribute('href')));
  assert.equal(catalogueLinks.length,30);assert(catalogueLinks.every(href=>href.startsWith(base)));
  await page.keyboard.press('Escape');await page.keyboard.press('Escape');
  await page.locator('[data-project="seton-crossing"] a').click();await page.waitForSelector('[data-primary-project]');
  await page.waitForLoadState('domcontentloaded');
  assert.equal(new URL(page.url()).pathname,base+'seton');
  assert.equal(await page.locator('.project-specification').evaluate(element=>element.previousElementSibling?.classList.contains('project-opening')),true);
  await expect(page.locator('.project-specification')).toHaveCount(1);
  await expect(page.locator('.next-project')).toHaveCSS('background-color','rgb(27, 28, 29)');
  await page.locator('[data-project-search]').first().click();
  await expect(page.locator('#site-search-dialog')).toBeVisible();
  await page.locator('#site-search-input').fill('D’Arcy');
  await expect(page.locator('[data-search-project]:visible')).toHaveCount(2);
  await expect(page.locator('[data-search-project="darcy"]')).toHaveAttribute('href',base+'darcy');
  const searchLinks=await page.locator('[data-search-project]').evaluateAll(els=>els.map(el=>el.getAttribute('href')));
  assert.equal(searchLinks.length,30);assert(searchLinks.every(href=>href.startsWith(base)));
  await page.keyboard.press('Escape');
  await expect(page.locator('#site-search-dialog')).not.toBeVisible();
  const imageCount=await page.locator('#project-gallery-data').evaluate(el=>JSON.parse(el.textContent).length);
  await page.locator('[data-gallery-index="0"]').click();await expect(page.locator('#viewer-count')).toHaveText(`1 / ${imageCount}`);
  await page.keyboard.press('Escape');
  await page.locator('[data-menu-trigger="services"]').click();await page.locator('[data-service-link="commercial"]').click();
  await page.waitForSelector('#tab-commercial[aria-expanded="true"]');
  assert.equal(new URL(page.url()).pathname,base);
  await page.goto(address+base+'darcy');
  await page.locator('#site-header .site-wordmark').click();
  await expect(page).toHaveURL(address+base+'#hero');
  await expect(page.locator('#hero-title')).toBeVisible();
  const motionContext=await browser.newContext({reducedMotion:'no-preference'});
  const motionPage=await motionContext.newPage();
  motionPage.on('pageerror',error=>errors.push(error.message));
  await motionPage.addInitScript(()=>{
    localStorage.setItem('pi-motion','system');
    window.homeEntrances=[];
    document.addEventListener('pi:home-return',event=>window.homeEntrances.push(event.detail.phase));
  });
  await motionPage.goto(address+base+'darcy');
  await motionPage.locator('#site-header .site-wordmark').click();
  await expect(motionPage).toHaveURL(address+base+'#hero');
  await expect(motionPage.locator('html')).toHaveAttribute('data-home-return','done');
  const entrances=await motionPage.evaluate(()=>window.homeEntrances);
  assert.equal(entrances.length,1);assert(['native','fallback'].includes(entrances[0]));
  await expect(motionPage.locator('.hero-copy')).toHaveCSS('opacity','1');
  await motionContext.close();
  await page.goto(address+base+'contact');
  await expect(page.locator('.desktop-nav [data-contact-link]')).toHaveAttribute('aria-current','page');
  await page.getByRole('radio',{name:'Commercial Plazas',exact:true}).check();
  await expect(page.locator('#inquiry-fields')).toHaveAttribute('data-open','true');
  await expect(page.locator('#inquiry-photo-caption')).toContainText('Seton Crossing');
  await expect(page.locator('#inquiry-photo-link')).toHaveAttribute('href',base+'seton');
  await page.goto(address+base+'about');
  await expect(page.locator('.desktop-nav a[aria-current="page"]')).toHaveText('About');
  await page.locator('[data-experience-filter="Commercial"]').click();
  await expect(page.locator('.experience-entry:visible')).toHaveCount(2);
  await expect(page.locator('.experience-link').filter({hasText:'Seton Crossing'})).toHaveAttribute('href',base+'seton');
  await expect(page.locator('.principal-detail').first()).toContainText('1996');
  await page.locator('#scope-tab-1').click();
  await expect(page.locator('#scope-panel-1')).toBeVisible();
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({base,pages:33,links:30,aboutPage:true,contactPage:true,pairedFeaturedViews:true,drawingViewer:true,navigationCatalogue:true,projectSearch:true,earlyProjectInformation:true,logoReturn:true,errors,passed:true}));
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
